nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.CutOutZarrDatasetNodes
      lam_dataset: /path/to/regional-dataset.zarr
      forcing_dataset: /path/to/global-dataset.zarr
      thinning: 25  # optional
    attributes: ...
  hidden: ...

edges: ...
