nodes:
  data: ...
  hidden: ...

edges:
  # A) Encoder connections
  - nodes:
      src_name: data
      dst_name: hidden
    edge_builder:
      _target_: aifs.graphs.edges.CutOffEdges
      cutoff_factor: 0.7
  # B) Decoder connections
  - nodes:
      src_name: hidden
      dst_name: hidden
    edge_builder:
      _target_: aifs.graphs.edges.KNNEdges
      nearest_neighbours: 3
