nodes:
  data: ...
  hidden: ...

edges:
  # A) Encoder connections
  - nodes:
      src_name: data
      dst_name: hidden
    edge_builder:
      _target_: aifs.graphs.edges.CutOffConnection
      cutoff_factor: 0.7
  # B) Decoder connections
  - nodes:
      src_name: hidden
      dst_name: hidden
    edge_builder:
      _target_: aifs.graphs.edges.KNNConnection
      nearest_neighbours: 3
 # C) Processor connections
  - nodes:
      src_name: hidden
      dst_name: data
    edge_builder:
      _target_: aifs.graphs.edges.KNNConnection
      nearest_neighbours: 3