nodes:
  data:
    node_builder:
      _target_: aifs.graphs.nodes.ZarrDatasetNodeBuilder
      dataset: /path/to/dataset.zarr
  hidden:
    node_builder:
      _target_: aifs.graphs.nodes.NPZFileNodeBuilder
      grid_definition_path: /path/to/grids/
      resolution: o48