nodes:
  data:
    node_builder:
      _target_: aifs.graphs.nodes.ZarrDatasetNodes
      dataset: /path/to/dataset.zarr
  hidden:
    node_builder:
      _target_: aifs.graphs.nodes.NPZFileNodes
      grid_definition_path: /path/to/grids/
      resolution: o48
