nodes:
  data:
    coords:
      _target_: aifs.graphs.nodes.nodes.ZarrDatasetNodeBuilder
      dataset: /path/to/dataset.zarr
    attributes:
      weights:
        _target_: aifs.graphs.nodes.weights.Area
        norm: unit-max
  hidden: ...
