nodes:
  data:
    coords:
      _target_: aifs.graphs.nodes.ZarrDatasetNodeBuilder
      dataset: /path/to/dataset.zarr
    attributes:
      weights:
        _target_: aifs.graphs.nodes.masks.MissingMask
        variable: lsm
        invert: true
  hidden: ...
