nodes:
  - name: data
    node_builder:
      _target_: aifs.graphs.nodes.nodes.ZarrDatasetNodeBuilder
      dataset: /path/to/dataset.zarr
      forcing_dataset: /path/to/forcing.zarr
    attributes:
      weights:
        _target_: aifs.graphs.nodes.masks.CutoutMask
  - name: hidden
